namespace FiddlerBackend.Contracts;

public enum NotificationType
{
	SnapshotCreated = 0,
	SnapshotDeleted = 1,
	SnapshotShared = 2,
	SnapshotUnshared = 3,
	SnapshotUpdated = 4,
	SnapshotNameUpdated = 5,
	SnapshotDescriptionUpdated = 6,
	SnapshotPasswordUpdated = 32,
	RuleSetShared = 7,
	RuleSetUnshared = 8,
	ComposerCollectionShared = 9,
	ComposerCollectionUnshared = 10,
	ComposerCollectionNameUpdated = 11,
	ComposerCollectionDeleted = 12,
	ComposerCollectionRequestDeleted = 13,
	ComposerCollectionRequestMoved = 14,
	ComposerCollectionRequestUpdated = 15,
	ComposerCollectionRequestCreated = 16,
	ComposerCollectionFolderDeleted = 17,
	ComposerCollectionFolderMoved = 18,
	ComposerCollectionFolderNameUpdated = 19,
	ComposerCollectionFolderCreated = 20,
	AccountActivated = 21,
	AccountDeactivated = 22,
	AccountCancelled = 30,
	AccountResumed = 31,
	AccountUpgraded = 33,
	AccountMigrated = 34,
	RuleSetDeleted = 23,
	CommentInSnapshotReplyCreated = 24,
	CommentInSnapshotCreated = 25,
	CommentInSnapshotUpdated = 26,
	CommentInSnapshotReplyUpdated = 27,
	CommentInSnapshotDeleted = 28,
	CommentInSnapshotReplyDeleted = 29,
	ResourceMoved = 35
}
